spring:
  application:
    name: MedicineService
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:medicine_service}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123321}
