spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp-mail.outlook.com
    username: medicine.service@outlook.com
    password: medicineservice1
    port: 587
    protocol: STARTTLS
    properties:
      mail:
        debug: true
      smtp:
        starttls:
          enable: true
          required: true

  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: 7203312

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
bot:
  name: ${bot.name}
  token: ${bot.token}
zoom:
  client-id: ${zoom.client-id}
  client-secret: ${zoom.client-secret}
  account-id: ${zoom.account-id}
server:
  port: 8080
